[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "flake8-comprehensions"
version = "3.10.0"
description = "A flake8 plugin to help you write better list/set/dict comprehensions."
authors = [{name = "Adam Johnson", email = "me@adamj.eu"}]
license = {text = "MIT"}
keywords = ["flake8", "comprehensions", "list comprehension", "set comprehension", "dict comprehension"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Flake8",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.7"
dependencies = [
    "flake8>=3.0,!=3.2.0",
    'importlib-metadata ; python_version < "3.8"',
]

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.urls]
Homepage = "https://github.com/adamchainz/flake8-comprehensions"
Changelog = "https://github.com/adamchainz/flake8-comprehensions/blob/main/HISTORY.rst"
Twitter = "https://twitter.com/adamchainz"

[project.entry-points."flake8.extension"]
C4 = "flake8_comprehensions:ComprehensionChecker"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.black]
target-version = ['py37']

[tool.isort]
profile = "black"
add_imports = "from __future__ import annotations"

[tool.mypy]
mypy_path = "src/"
show_error_codes = true
strict = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true

[tool.pytest.ini_options]
addopts = """\
    --strict-config
    --strict-markers
    """
